# Generated by Django 5.2 on 2025-05-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='support_tickets/%Y/%m/%d/'),
        ),
    ]
