# Generated by Django 5.2 on 2025-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='created_by',
            field=models.EmailField(default='anonim@n.com', max_length=254),
        ),
    ]
